### ISSUE TITLE
Deleting/Modifying quick launch configurations does not work.

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#11]
Deleting/Modifying quick launch configurations does not work. When you select a quick launch configuration then delete it, it will disappear from the screen, but you are still able to select it from the list as if it wasn't deleted.

**In addition, modifying them will create an entirely new launch configuration with those settings.**

****NOTE:** This issue does not seem to occur with newly created launch configurations and only seems to occur with old ones that were created before the migration.**

In terms of the HTTP request, it is sending null for the id.

![](https://i.imgur.com/TKA5BA3.png)
![](https://i.imgur.com/Pw9rrjT.gif)

**Comment by MaddoxDevelopment** [comment]
Gotcha, looks like they don't have an id for some reason. Migration may have failed, i'll take a look.

**Comment by MaddoxDevelopment** [comment]
Fixed.
