### ISSUE TITLE
RSPeer landing page is missing links to other pages such as community, bot panel, script docs, etc.

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#13]
RSPeer landing page is missing links to other pages such as community, bot panel, script docs, etc.

**Comment by MaddoxDevelopment** [comment]
I did this on purpose so they use app.rspeer.org.

**Comment by Sphiinx** [comment]
If someone new finds the community from google or another source, how will they get to the app panel from the homepage? It didn't seem very intuitive on where to go from the landing page in terms of a new user?

**Comment by MaddoxDevelopment** [comment]
They just need to click the "Get Started" button.
