### ISSUE TITLE
RSPeer loader link key GUI links to old bot page.

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#14]
RSPeer loader link key GUI links to old bot page. It says "Visit https://bot.rspeer.org to retrieve it." when it should be "Visit https://app.rspeer.org/#/bot/management to retrieve it."

![](https://i.imgur.com/OecP0aj.png)

**Comment by MaddoxDevelopment** [comment]
Left this so it fits on the prompt. Its redirected to the new one anyway.
