### ISSUE TITLE
RSPeer client login screen click here to register links to the old authentication

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#17]
RSPeer client login screen click here to register links to the old authentication. It links to "https://sso.rspeer.org/" when it should link to "https://auth.rspeer.org/?redirect=https://app.rspeer.org"

![](https://i.imgur.com/iI2X1js.png)

**Comment by MaddoxDevelopment** [comment]
Closing this because it should be redirecting like the other routes.
