### ISSUE TITLE
RSPeer landing page does not use or remember dark mode settings

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#20]
RSPeer landing page does not use or remember dark mode settings
It should also be dark mode by default.

![](https://i.imgur.com/hABHZEX.png)

**Comment by MaddoxDevelopment** [comment]
Thats saying to switch to light mode. So it does know you are on dark mode.

**Comment by Sphiinx** [comment]
@MaddoxDevelopment I meant that it needs to be added to the RSPeer landing/home page so you can turn that to dark mode too.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
