### ISSUE TITLE
Deleting/Modifying a proxy does nothing and does it send any http requests.

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#21]
Deleting a proxy does nothing and does it send any http requests. When you click the delete button, nothing happens.

**In addition, modifying them will create an entirely new proxy with those settings.**

****NOTE:** This only happens with proxies that were created before the migration!**

![](https://i.imgur.com/c6JV5Gy.gif)

**Comment by MaddoxDevelopment** [comment]
Fixed.
