### ISSUE TITLE
Launching the rspeer launcher opens the old launcher page.

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#8]
Launching the RSPeer launching opens the old launcher page at https://bot.rspeer.org/ when it should open https://app.rspeer.org/#/bot/management

**Comment by MaddoxDevelopment** [comment]
All these routes are setup to redirect, is it not redirecting for you ? @Sphiinx

**Comment by Sphiinx** [comment]
@MaddoxDevelopment I took a further look and it seems Firefox’s default tracking and security blocking prevents the redirect unless you allow special permissions.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MaddoxDevelopment** [comment]
I'm using firefox though and it works just fine.

**Comment by Sphiinx** [comment]
Do you have an exception added in your settings? If not perhaps my security settings are set more strictly if so this can be closed.

- ![GitHawk Upload by Sphiinx](https://i.imgur.com/bkgMk0Q.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MaddoxDevelopment** [comment]
Nah i dont have any special exceptions, just default firefox.

**Comment by MaddoxDevelopment** [comment]
Closing as it should be redirecting. Feel free to re-open if it is not.
