### ISSUE TITLE
If you have a pending script update, you cannot submit another update to the same script until the first is approved/denied.

### ISSUE THREAD

**Issue by Sphiinx** [MaddoxDevelopment/RSPeer-Api#9]
If you have a pending script update, you cannot submit another update to the same script to overwrite the last until the first is approved/denied.

![](https://i.imgur.com/bRPRy1f.png)
![](https://i.imgur.com/4kBcYwc.png)

**Comment by MaddoxDevelopment** [comment]
This should be fixed now.
